spring:
  datasource:
    url: jdbc:mysql://sishengjie.xyz:3306/lweci?characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    #开发环境关闭缓存，便于运行时调试页面
    #生产环境开启缓存，加速首次之后的访问
    cache: true
  jpa:
    open-in-view: false
    show-sql: false #开发阶段打开语句展示
server:
  port: 80                        #https默认端口443
  servlet:
    context-path: /book                     #项目根路径
    session:
      tracking-modes: cookie     #解决Url最后末尾带有jSessionId=...的问题
#  ssl:
#    key-store: 3162778_sishengjie.xyz.pfx   #CA证书
#    key-store-password: 9E03Qu38            #CA密码